version: 0.1.3.{build}
skip_non_tags: true
before_build:
- cmd: nuget restore
- ps: >-
    cd C:\projects\videoffice

    $VerFromAssemblyInfo = get-content SemVerInfo.cs

    $InstallScript = get-content Install\VideOffice.iss

    $VerFromAssemblyInfo[2][27]

    $i = 27

    $verString = ""

    do

    {

    $verString = $verString + $VerFromAssemblyInfo[2][$i]

    $i = $i + 1

    }

    while($VerFromAssemblyInfo[2][$i] -ne ')')

    $verString

    $InstallScript[1]

    $InstallScript[1] = "#define Version " + $verString

    $InstallScript[1]

    $InstallScript | set-content Install\VideOffice.iss
build:
  project: VideOffice.sln
  publish_wap: true
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
after_build:
- cmd: packages\Tools.InnoSetup.5.5.6\tools\ISCC Install\VideOffice.iss
artifacts:
- path: VideOffice\Install\Installer
  type: WebDeployPackage
deploy:
- provider: GitHub
  tag: $(appveyor_tag_version)
  release: $(appveyor_tag_version)
  description: VideOffice Release from AppVeyor
  auth_token:
    secure: ZjkHlkSYF+1A2xfv8oVVupjQMKjJo51/CldzdQEsifZJGGSF8/jrR+g4OTfSc8SJ
  artifact: VideOffice\Install\Installer.zip